### ISSUE TITLE
All server output is quadrupled

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-adapters#222] opened 2019-02-01 07:56 UTC
Every line of server output shows up 4 times, I guess there are too many listeners attached.

**Comment by robstryker** [comment] 2019-02-04 22:37
The 4 outputs are NOT caused by the dozen or so random connections. Those connections are for polling, and basically swallow any output they receive. 

However, there are two bugs that cause this.  

1) There is a duplicate "client.connect()" call in vscode-adapters. So there are two official connections being made. 

2) A bug in rsp-server for runtime output only causes each line of output to be sent to a client twice. 

Combine these together, and a line of output is sent twice to each client, and there are two clients fully registered in the model, so 4x of all output.

**Comment by dgolovin** [comment] 2019-02-05 00:40
Related to #71.

**Comment by adietish** [comment] 2019-02-26 13:23
A partial fix for this was applied in rsp-server: https://github.com/redhat-developer/rsp-server/pull/226

**Comment by adietish** [comment] 2019-02-26 13:24
@robstryker what's remaining to be done here?

**Comment by adietish** [comment] 2019-02-26 13:24
moving to devex #163

**Comment by robstryker** [comment] 2019-02-26 14:42
This is done.

**Closed by robstryker** 2019-02-26 14:42 UTC
Labels: bug
